[package]
name = "txfs"
version = "0.1.0"
authors = ["code@tinychain.net"]
edition = "2021"
license = "Apache-2.0"
description = "A cached transactional filesystem layer over tokio::fs"
repository = "https://github.com/haydnv/txfs"
readme = "README.md"

categories = ["caching", "data-structures", "filesystem", "memory-management"]
keywords = ["transactional", "file", "io", "cache"]

[features]
logging = ["log"]

[dependencies]
freqfs = { path = "../freqfs" }
futures = "0.3"
log = { version = "0.4", features = ["release_max_level_info"], optional = true }
safecast = "0.1"
txn_lock = { path = "../txn_lock" }
